geometry:
  type: cartesian
  bounds: {x1min: 0., x1max: 10.e3, x2min: 0., x2max: 20.e3, x3min: 0., x3max: 10.e3}
  cells: {nx1: 100, nx2: 300, nx3: 150, nghost: 3}
  center_latitude: 30.
  center_longitude: -110.

integration:
  type: rk3
  cfl: 0.45
  implicit-scheme: 0
  nlim: -1
  tlim: 8640
  start-date: 2024-01-01
  end-date: 2024-01-02
